# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

resources:
- repo: self

variables:
 - name: dockerRegistryServiceConnection
   value: '805e423a-a0e7-41c8-a8e7-a1828d65300d'
 - name: imageRepository
   value: 'products-microservice' 
 - name: containerRegistry
   value: 'akshatecommerceregistry.azurecr.io' 
 - name: dockerFilePath
   value: '$(Build.SourcesDirectory)/ProductsMicroservice.API/Dockerfile' 
 - name: tag
   value: '$(Build.BuildId)'
 - name: vmImageName
   value: 'ubuntu-latest' 

stages:
 - stage: Build
   displayName: Build and push stage
   jobs:
   - job: Build
     displayName: Docker Build
     pool:
      vmImage: $(vmImageName)
     steps:
     - task: Docker@2
       displayName: Build and push an image to ecommerce registry
       inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerFilePath)
        buildContext: $(Build.SourcesDirectory)     
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

 - stage: Test
   displayName: Test and publish results stage