apiVersion: v1
kind: Service
metadata:
 name: apigateway
 namespace: ecommerce-namespace
spec:
 selector:
  app: apigateway
 ports:
  - protocol: TCP
    port: 8080  # The port that the API Gateway will be exposed on
    targetPort: 8080 # The port that the API Gateway container is listening on
 type: LoadBalancer # Expose the API Gateway externally using a LoadBalancer service type